name: cryptowallet
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

  fluttertoast: ^8.2.4
  sizer: ^2.0.15
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  web: any

  permission_handler: ^12.0.1

  mobile_scanner: ^6.0.10
  http: ^1.4.0
  smooth_page_indicator: ^1.2.1
  bip39: ^1.0.6
  syncfusion_flutter_charts: ^29.1.38
  graphic: ^2.6.0
  clipboard: ^2.0.2

  qr_flutter: ^4.1.0
  share_plus: ^11.1.0
  provider: ^6.1.5+1
  flutter_secure_storage: ^9.2.4
  web_socket_channel: ^2.1.0
  flutter_dotenv: ^6.0.0
  local_auth: ^2.3.0
  webview_flutter: ^4.13.0
  file_picker: ^10.3.3
  socket_io_client: ^3.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

    - assets/currencyicons/

    - assets/iconsforcard/
